CREATE TABLE IF NOT EXISTS voice_recording_recipients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  recording_id BIGINT UNSIGNED NOT NULL,
  sender_account_id INT NOT NULL,
  sender_person_id INT NULL,
  clan_id INT NULL,
  receiver_account_id INT NULL,
  receiver_person_id INT NULL,
  transcript_snapshot LONGTEXT NULL,
  audio_storage_path VARCHAR(1000) NOT NULL,
  send_status ENUM('pending','sent','failed','cancelled') NOT NULL DEFAULT 'pending',
  scheduled_at DATETIME NULL,
  sent_at DATETIME NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_vrr_recording (recording_id),
  KEY idx_vrr_sender_account (sender_account_id),
  KEY idx_vrr_receiver_account (receiver_account_id),
  KEY idx_vrr_receiver_person (receiver_person_id),
  KEY idx_vrr_clan_status_scheduled (clan_id, send_status, scheduled_at),
  CONSTRAINT fk_vrr_recording FOREIGN KEY (recording_id) REFERENCES recordings(id) ON DELETE CASCADE,
  CONSTRAINT fk_vrr_sender_account FOREIGN KEY (sender_account_id) REFERENCES accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_vrr_sender_person FOREIGN KEY (sender_person_id) REFERENCES people(id) ON DELETE SET NULL,
  CONSTRAINT fk_vrr_receiver_account FOREIGN KEY (receiver_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_vrr_receiver_person FOREIGN KEY (receiver_person_id) REFERENCES people(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
